locale                   : "de-DE"
title                    : "My Repair Blog"
#title_separator          : "-"
#name                     : &name "Your Name"
#description              : &description "personal description"
#theme: minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

